version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - deepseek

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always

  deepseek:
    build: ./models/deepseek
    restart: always
    # port mapping ถ้าโมเดลให้บริการ API ภายใน container
    ports:
      - "8500:8500"

  # เพิ่ม services สำหรับโมเดลอื่น ๆ ที่คุณมีในอนาคต
