version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always

  deepseek:
    build: ./models/deepseek
    restart: always
  # เพิ่ม service สำหรับโมเดลอื่น ๆ ในอนาคต
