name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Frontend Image
        run: |
          docker build -t frontend:latest -f frontend/Dockerfile frontend

      - name: Build Backend Image
        run: |
          docker build -t backend:latest -f backend/Dockerfile backend

      - name: Build DeepSeek Model Image
        run: |
          docker build -t ai-model:deepseek -f models/deepseek/Dockerfile models/deepseek

      - name: Run Tests
        run: |
          echo "Running tests..."
          # เพิ่มคำสั่งสำหรับ unit/integration tests ที่เตรียมไว้

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/deployment
            docker-compose pull
            docker-compose up -d
